[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.4.0"
prost = "0.13.4"
prost-types = "0.13.4"
solana-perf = "=2.1.6"
solana-sdk = "=2.1.6"
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
